# Generated by Django 3.1.7 on 2021-02-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FullName')),
                ('designation', models.CharField(blank=True, choices=[('ProjectManager', 'ProjectManager'), ('BackendDeveloper', 'BackendDeveloper'), ('FrontendDeveloper', 'FrontendDeveloper'), ('Designer', 'Designer')], db_index=True, default='BackendDeveloper', max_length=30, null=True, verbose_name='Designation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='EmpManager.employee')),
            ],
        ),
    ]
